(()=>{
'use strict';
const KEY='cricpro_v3';
const DEFAULT={teams:[],matches:[],competitions:[]};
let db=load(), page='home', active=null;
const $=id=>document.getElementById(id);
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const clone=o=>JSON.parse(JSON.stringify(o));
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&Array.isArray(x.teams)?Object.assign(clone(DEFAULT),x):clone(DEFAULT)}catch(e){return clone(DEFAULT)}}
function persist(){localStorage.setItem(KEY,JSON.stringify(db))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),1700)}
function team(id){return db.teams.find(t=>t.id===id)} function match(id){return db.matches.find(m=>m.id===id)}
function ballsToOver(n){return Math.floor(n/6)+'.'+(n%6)}
function legalBalls(i){return i.balls.filter(b=>b.legal).length}
function runs(i){return i.balls.reduce((s,b)=>s+b.total,0)}
function wickets(i){return i.balls.filter(b=>b.wicket&&b.wicket.type!=='retired hurt').length}
function batterStats(i,pid){let r=0,b=0,f=0,s=0,out='not out';for(const x of i.balls){if(x.striker===pid){r+=x.bat;if(x.legal)b++;if(x.bat===4)f++;if(x.bat===6)s++}if(x.wicket&&x.wicket.player===pid&&x.wicket.type!=='retired hurt')out=x.wicket.type}return{r,b,f,s,sr:b?(r*100/b).toFixed(1):'0.0',out}}
function bowlerStats(i,pid){let b=0,r=0,w=0;for(const x of i.balls){if(x.bowler!==pid)continue;if(x.legal)b++;r+=x.bowlerRuns;if(x.wicket&&['bowled','caught','lbw','stumped','hit wicket'].includes(x.wicket.type))w++}return{b,r,w,econ:b?(r/(b/6)).toFixed(2):'0.00'}}
function modal(html){const d=document.createElement('div');d.id='modalback';d.className='modalback';d.innerHTML=`<div class="modal">${html}</div>`;d.addEventListener('click',e=>{if(e.target===d)d.remove()});document.body.appendChild(d);return d}
function closeModal(){const m=$('modalback');if(m)m.remove()}
function header(){return `<header class="top"><div class="brand">CRICPRO SCORE<small>SMART CRICKET SCORER</small></div><button class="icon" data-act="backup">⇩</button></header>`}
const navs=[['home','⌂','Home'],['matches','▣','Matches'],['teams','♟','Teams'],['events','♛','Events'],['stats','★','Stats']];
function tabs(){return `<nav class="tabs"><div class="tabsin">${navs.map(n=>`<div class="tab ${page===n[0]?'active':''}" data-nav="${n[0]}"><b>${n[1]}</b>${n[2]}</div>`).join('')}</div></nav>`}
function render(){const a=$('app');a.className='app';a.innerHTML=header()+`<main class="view">${screen()}</main>`+tabs()}
function screen(){if(page==='home')return home();if(page==='teams')return teams();if(page==='matches')return matches();if(page==='events')return events();if(page==='stats')return stats();if(page==='score'&&active)return score(match(active));return home()}
function home(){const live=db.matches.filter(m=>m.status==='live');return `<section class="hero"><div class="muted">WELCOME TO</div><h1>Cricket scoring,<br><span class="green">made effortless.</span></h1><p class="muted">2–50 over matches, offline scoring, leagues and tournaments.</p><button class="btn" data-act="newMatch">＋ Start a Match</button></section><div class="section">Quick actions</div><div class="grid"><div class="card action" data-act="newMatch"><span>🏏</span><b>New Match</b><small class="muted">Single / league</small></div><div class="card action" data-act="newEvent"><span>🏆</span><b>Tournament</b><small class="muted">League / knockout</small></div><div class="card action" data-nav="teams"><span>👥</span><b>Teams</b><small class="muted">Squads & CSV</small></div><div class="card action" data-nav="stats"><span>📊</span><b>Statistics</b><small class="muted">Runs & wickets</small></div></div>${live.length?`<div class="section">Live matches</div><div class="list">${live.map(matchItem).join('')}</div>`:''}`}
function teams(){return `<div class="row between"><div><h2>Teams & Players</h2><p class="muted">Create manually or import CSV</p></div><button class="btn" data-act="newTeam">＋ Team</button></div><div class="card"><b>CSV player import</b><p class="muted">Columns: team, player, role</p><input id="csvFile" type="file" accept=".csv,text/csv"><button class="btn secondary" style="margin-top:8px" data-act="importCSV">Import CSV</button></div><div class="list">${db.teams.length?db.teams.map(t=>`<div class="listitem" data-team="${t.id}"><div class="row between"><b>${esc(t.name)}</b><span class="badge">${t.players.length} players</span></div><small class="muted">${esc(t.short)}</small></div>`).join(''):'<div class="empty">No teams created.</div>'}</div>`}
function matches(){return `<div class="row between"><div><h2>Matches</h2><p class="muted">Saved matches</p></div><button class="btn" data-act="newMatch">＋</button></div><div class="list">${db.matches.length?db.matches.slice().reverse().map(matchItem).join(''):'<div class="empty">No matches yet.</div>'}</div>`}
function matchItem(m){const a=team(m.teamA),b=team(m.teamB),i=m.innings[m.currentInnings||0];return `<div class="listitem" data-match="${m.id}"><div class="row between"><b>${esc(a?.name)} vs ${esc(b?.name)}</b><span class="badge ${m.status==='live'?'live':m.status==='done'?'done':''}">${m.status.toUpperCase()}</span></div><small class="muted">${m.overs} overs · ${esc(m.type)}</small>${i?`<div><b>${runs(i)}/${wickets(i)}</b> <span class="muted">(${ballsToOver(legalBalls(i))})</span></div>`:''}</div>`}
function events(){return `<div class="row between"><div><h2>Competitions</h2><p class="muted">League & knockout</p></div><button class="btn" data-act="newEvent">＋</button></div><div class="list">${db.competitions.length?db.competitions.map(c=>`<div class="listitem" data-event="${c.id}"><div class="row between"><b>${esc(c.name)}</b><span class="badge">${esc(c.format)}</span></div><small class="muted">${c.teamIds.length} teams · ${c.overs} overs</small></div>`).join(''):'<div class="empty">No competitions yet.</div>'}</div>`}
function stats(){let rr={},ww={};for(const m of db.matches)for(const i of m.innings){for(const p of team(i.battingTeam)?.players||[]){rr[p.id]=rr[p.id]||{n:p.name,v:0};rr[p.id].v+=batterStats(i,p.id).r}for(const p of team(i.bowlingTeam)?.players||[]){ww[p.id]=ww[p.id]||{n:p.name,v:0};ww[p.id].v+=bowlerStats(i,p.id).w}}const top=o=>Object.values(o).sort((a,b)=>b.v-a.v).slice(0,10);return `<h2>Statistics</h2><div class="grid"><div class="card"><small class="muted">Matches</small><h2>${db.matches.length}</h2></div><div class="card"><small class="muted">Teams</small><h2>${db.teams.length}</h2></div></div>${leader('Top Run Scorers',top(rr),'Runs')}${leader('Top Wicket Takers',top(ww),'Wkts')}`}
function leader(title,a,col){return `<div class="section">${title}</div><div class="card tablewrap"><table class="table"><tr><th>Player</th><th class="right">${col}</th></tr>${a.map(x=>`<tr><td>${esc(x.n)}</td><td class="right"><b>${x.v}</b></td></tr>`).join('')||'<tr><td colspan="2">No data</td></tr>'}</table></div>`}
function newTeam(){modal(`<div class="row between"><h2>New Team</h2><button class="icon" data-act="close">✕</button></div><div class="field"><label>TEAM NAME</label><input id="tn" autocomplete="off"></div><div class="field"><label>SHORT NAME</label><input id="ts" maxlength="5"></div><div class="field"><label>PLAYERS — ONE PER LINE</label><textarea id="tp" placeholder="Player 1\nPlayer 2\nPlayer 3"></textarea></div><button class="btn block" data-act="saveTeam">Save Team</button>`)}
function saveTeam(){const n=$('tn'),s=$('ts'),p=$('tp');if(!n||!s||!p)return toast('Form error');const name=n.value.trim();if(!name)return toast('Enter team name');const names=p.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(names.length<2)return toast('Add at least 2 players');if(db.teams.some(t=>t.name.toLowerCase()===name.toLowerCase()))return toast('Team name already exists');db.teams.push({id:uid(),name,short:(s.value.trim()||name.slice(0,3)).toUpperCase(),players:names.map(x=>({id:uid(),name:x,role:'Player'}))});persist();closeModal();render();toast('Team saved')}
function editTeam(id){const t=team(id);if(!t)return;modal(`<div class="row between"><h2>${esc(t.name)}</h2><button class="icon" data-act="close">✕</button></div><div class="list">${t.players.map(p=>`<div class="listitem"><div class="row between"><b>${esc(p.name)}</b><button class="icon" data-remove-player="${p.id}" data-team-id="${t.id}">✕</button></div><small class="muted">${esc(p.role||'Player')}</small></div>`).join('')}</div><div class="field"><label>ADD PLAYER</label><input id="newp"></div><button class="btn block" data-add-player="${t.id}">Add Player</button>`)}
function addPlayer(id){const t=team(id),e=$('newp');if(!t||!e)return;const n=e.value.trim();if(!n)return toast('Enter player name');if(t.players.some(p=>p.name.toLowerCase()===n.toLowerCase()))return toast('Player already exists');t.players.push({id:uid(),name:n,role:'Player'});persist();closeModal();editTeam(id)}
function removePlayer(tid,pid){const t=team(tid);if(!t)return;if(t.players.length<=2)return toast('Keep at least 2 players');t.players=t.players.filter(p=>p.id!==pid);persist();closeModal();editTeam(tid)}
function importCSV(){const f=$('csvFile')?.files?.[0];if(!f)return toast('Choose CSV file');const r=new FileReader();r.onload=()=>{let count=0;const lines=String(r.result).split(/\r?\n/).filter(x=>x.trim());if(lines[0]&&/team/i.test(lines[0]))lines.shift();for(const line of lines){const [tn,pn,role]=line.split(',').map(x=>(x||'').trim());if(!tn||!pn)continue;let t=db.teams.find(x=>x.name.toLowerCase()===tn.toLowerCase());if(!t){t={id:uid(),name:tn,short:tn.slice(0,3).toUpperCase(),players:[]};db.teams.push(t)}if(!t.players.some(p=>p.name.toLowerCase()===pn.toLowerCase())){t.players.push({id:uid(),name:pn,role:role||'Player'});count++}}persist();render();toast(`${count} players imported`)};r.onerror=()=>toast('Could not read CSV');r.readAsText(f)}
function newMatch(){if(db.teams.length<2){modal(`<h2>Create teams first</h2><p class="muted">At least two teams are required.</p><button class="btn block" data-nav="teams">Go to Teams</button>`);return}modal(`<div class="row between"><h2>New Match</h2><button class="icon" data-act="close">✕</button></div><div class="field"><label>MATCH TYPE</label><select id="mt"><option>Single Match</option><option>League</option><option>Tournament</option><option>Knockout</option><option>Practice</option></select></div><div class="field"><label>TEAM A</label><select id="ma">${db.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></div><div class="field"><label>TEAM B</label><select id="mb">${db.teams.map((t,i)=>`<option value="${t.id}" ${i===1?'selected':''}>${esc(t.name)}</option>`).join('')}</select></div><div class="field"><label>OVERS (2–50)</label><input id="mo" type="number" min="2" max="50" value="10"></div><div class="field"><label>VENUE</label><input id="mv"></div><button class="btn block" data-act="createMatch">Continue to Toss</button>`)}
function createMatch(){const ma=$('ma'),mb=$('mb'),mo=$('mo'),mt=$('mt'),mv=$('mv');if(!ma||!mb||!mo)return toast('Form error');if(ma.value===mb.value)return toast('Select different teams');const o=Math.max(2,Math.min(50,parseInt(mo.value)||10));const m={id:uid(),teamA:ma.value,teamB:mb.value,overs:o,type:mt.value,venue:mv.value.trim(),status:'setup',created:Date.now(),innings:[],currentInnings:0};db.matches.push(m);persist();closeModal();toss(m.id)}
function toss(id){const m=match(id),a=team(m.teamA),b=team(m.teamB);modal(`<h2>Toss</h2><div class="field"><label>WON BY</label><select id="tw"><option value="${a.id}">${esc(a.name)}</option><option value="${b.id}">${esc(b.name)}</option></select></div><div class="field"><label>DECISION</label><select id="td"><option value="bat">Bat</option><option value="bowl">Bowl</option></select></div><button class="btn block" data-start-match="${id}">Start Match</button>`)}
function startMatch(id){const m=match(id),tw=$('tw'),td=$('td');if(!m||!tw||!td)return toast('Toss form error');const winner=tw.value,bat=td.value==='bat'?winner:(winner===m.teamA?m.teamB:m.teamA),bowl=bat===m.teamA?m.teamB:m.teamA;const bt=team(bat),bw=team(bowl);if(bt.players.length<2||bw.players.length<1)return toast('Teams need players');m.toss={winner,decision:td.value};m.status='live';m.currentInnings=0;m.innings=[newInn(bat,bowl)];persist();closeModal();active=id;page='score';render()}
function newInn(bat,bowl){const bt=team(bat),bw=team(bowl);return{battingTeam:bat,bowlingTeam:bowl,balls:[],striker:bt.players[0].id,nonStriker:bt.players[1].id,bowler:bw.players[0].id,nextBatter:2,completed:false}}
function score(m){const i=m.innings[m.currentInnings];if(!i)return '<div class="empty">Match data unavailable.</div>';const bt=team(i.battingTeam),bw=team(i.bowlingTeam),lb=legalBalls(i),r=runs(i),w=wickets(i),target=m.currentInnings===1?runs(m.innings[0])+1:null,remain=m.overs*6-lb,need=target?Math.max(0,target-r):null,crr=lb?(r/(lb/6)).toFixed(2):'0.00',rrr=target&&remain>0?(need/(remain/6)).toFixed(2):'—';const s=batterStats(i,i.striker),n=batterStats(i,i.nonStriker),bo=bowlerStats(i,i.bowler);const last=i.balls.slice(-8);return `<div class="row between"><div><h2>${esc(bt.name)}</h2><small class="muted">vs ${esc(bw.name)} · ${m.overs} overs</small></div><button class="icon" data-act="scorecard">Scorecard</button></div><div class="card scorebox"><div class="score">${r}/${w}</div><div class="muted">${ballsToOver(lb)} overs</div><div class="metrics"><div class="metric">CRR<b>${crr}</b></div><div class="metric">${target?'TARGET':'OVERS'}<b>${target||m.overs}</b></div><div class="metric">${target?'RRR':'WICKETS'}<b>${target?rrr:w}</b></div></div>${target?`<p class="muted" style="margin:10px 0 0">Need <b class="gold">${need}</b> from <b>${remain}</b> balls</p>`:''}</div><div class="players"><div class="player active"><b>${esc(bt.players.find(p=>p.id===i.striker)?.name||'Striker')} *</b><small>${s.r} (${s.b}) · SR ${s.sr}</small></div><div class="player"><b>${esc(bt.players.find(p=>p.id===i.nonStriker)?.name||'Non-striker')}</b><small>${n.r} (${n.b}) · SR ${n.sr}</small></div></div><div class="card"><div class="row between"><b>${esc(bw.players.find(p=>p.id===i.bowler)?.name||'Bowler')}</b><small class="muted">${ballsToOver(bo.b)} · ${bo.r} runs · ${bo.w} wkts</small></div></div><div class="balls">${last.map(b=>`<span class="ball">${esc(b.label)}</span>`).join('')||'<span class="muted">No balls yet</span>'}</div><div class="section">Runs</div><div class="scoring">${[0,1,2,3,4,6].map(x=>`<button class="scorebtn ${x===4||x===6?'bound':''}" data-run="${x}">${x}</button>`).join('')}<button class="scorebtn wicket" data-act="wicket">W</button><button class="scorebtn" data-act="undo">↶</button></div><div class="section">Extras</div><div class="scoring"><button class="scorebtn" data-extra="wide">WD</button><button class="scorebtn" data-extra="noball">NB</button><button class="scorebtn" data-extra="bye">B</button><button class="scorebtn" data-extra="legbye">LB</button></div><div class="row wrap" style="margin-top:12px"><button class="btn secondary" data-act="swap">Swap strike</button><button class="btn secondary" data-act="changeBowler">Change bowler</button><button class="btn danger" data-act="endInnings">End innings</button></div>`}
function addBall(kind,val=0){const m=match(active),i=m?.innings[m.currentInnings];if(!m||!i||i.completed)return;let b={striker:i.striker,nonStriker:i.nonStriker,bowler:i.bowler,legal:true,bat:0,total:0,bowlerRuns:0,label:'0'};if(kind==='run'){b.bat=val;b.total=val;b.bowlerRuns=val;b.label=String(val)}else if(kind==='wide'){b.legal=false;b.total=1;b.bowlerRuns=1;b.label='WD'}else if(kind==='noball'){b.legal=false;b.total=1;b.bowlerRuns=1;b.label='NB'}else if(kind==='bye'){b.total=1;b.label='B'}else if(kind==='legbye'){b.total=1;b.label='LB'}i.balls.push(b);const runForStrike=kind==='run'?val:(kind==='bye'||kind==='legbye'?1:0);if(runForStrike%2===1)[i.striker,i.nonStriker]=[i.nonStriker,i.striker];if(b.legal&&legalBalls(i)%6===0)[i.striker,i.nonStriker]=[i.nonStriker,i.striker];checkAutoEnd(m,i);persist();render()}
function wicket(){const m=match(active),i=m?.innings[m.currentInnings],bt=i&&team(i.battingTeam);if(!i)return;modal(`<h2>Wicket</h2><div class="field"><label>TYPE</label><select id="wt"><option>bowled</option><option>caught</option><option>lbw</option><option>stumped</option><option>run out</option><option>hit wicket</option><option>retired hurt</option></select></div><div class="field"><label>BATTER</label><select id="wp"><option value="${i.striker}">${esc(bt.players.find(p=>p.id===i.striker)?.name)}</option><option value="${i.nonStriker}">${esc(bt.players.find(p=>p.id===i.nonStriker)?.name)}</option></select></div><button class="btn block" data-act="confirmWicket">Confirm Wicket</button>`)}
function confirmWicket(){const m=match(active),i=m.innings[m.currentInnings],wt=$('wt'),wp=$('wp');if(!wt||!wp)return;const out=wp.value,type=wt.value;i.balls.push({striker:i.striker,nonStriker:i.nonStriker,bowler:i.bowler,legal:true,bat:0,total:0,bowlerRuns:0,label:'W',wicket:{player:out,type}});if(type!=='retired hurt'){const bt=team(i.battingTeam);if(i.nextBatter<bt.players.length){const np=bt.players[i.nextBatter++].id;if(out===i.striker)i.striker=np;else i.nonStriker=np}else i.completed=true}if(legalBalls(i)%6===0)[i.striker,i.nonStriker]=[i.nonStriker,i.striker];closeModal();checkAutoEnd(m,i);persist();render()}
function checkAutoEnd(m,i){const target=m.currentInnings===1?runs(m.innings[0])+1:null;if(legalBalls(i)>=m.overs*6||wickets(i)>=Math.max(1,team(i.battingTeam).players.length-1)||(target&&runs(i)>=target)){i.completed=true;finishInnings(m)}}
function finishInnings(m){const i=m.innings[m.currentInnings];i.completed=true;if(m.currentInnings===0){const bat=i.bowlingTeam,bowl=i.battingTeam;m.currentInnings=1;m.innings.push(newInn(bat,bowl));toast(`Target ${runs(i)+1}`)}else{m.status='done';m.result=resultText(m);toast(m.result)}persist()}
function resultText(m){const a=m.innings[0],b=m.innings[1],ra=runs(a),rb=runs(b);if(rb>ra)return `${team(b.battingTeam).name} won by ${Math.max(0,team(b.battingTeam).players.length-1-wickets(b))} wickets`;if(ra>rb)return `${team(a.battingTeam).name} won by ${ra-rb} runs`;return 'Match tied'}
function undo(){const m=match(active),i=m?.innings[m.currentInnings];if(!i||!i.balls.length)return toast('Nothing to undo');i.balls.pop();i.completed=false;persist();render();toast('Last ball undone')}
function swap(){const m=match(active),i=m?.innings[m.currentInnings];if(!i)return;[i.striker,i.nonStriker]=[i.nonStriker,i.striker];persist();render()}
function changeBowler(){const m=match(active),i=m?.innings[m.currentInnings],bw=i&&team(i.bowlingTeam);if(!i)return;modal(`<h2>Change Bowler</h2><div class="field"><select id="newBowler">${bw.players.map(p=>`<option value="${p.id}" ${p.id===i.bowler?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><button class="btn block" data-act="setBowler">Set Bowler</button>`)}
function setBowler(){const m=match(active),i=m?.innings[m.currentInnings],e=$('newBowler');if(i&&e){i.bowler=e.value;persist();closeModal();render()}}
function scorecard(){const m=match(active);modal(`<div class="row between"><h2>Scorecard</h2><button class="icon" data-act="close">✕</button></div>${m.innings.map((i,idx)=>innCard(i,idx)).join('')}${m.result?`<div class="card"><b>${esc(m.result)}</b></div>`:''}`)}
function innCard(i,idx){const bt=team(i.battingTeam),bw=team(i.bowlingTeam);return `<div class="card"><h3>${esc(bt.name)} — ${runs(i)}/${wickets(i)} (${ballsToOver(legalBalls(i))})</h3><div class="tablewrap"><table class="table"><tr><th>Batter</th><th>R</th><th>B</th><th>4</th><th>6</th><th>SR</th></tr>${bt.players.map(p=>{const z=batterStats(i,p.id);return `<tr><td>${esc(p.name)}</td><td>${z.r}</td><td>${z.b}</td><td>${z.f}</td><td>${z.s}</td><td>${z.sr}</td></tr>`}).join('')}</table></div><div class="tablewrap"><table class="table"><tr><th>Bowler</th><th>O</th><th>R</th><th>W</th><th>Econ</th></tr>${bw.players.map(p=>{const z=bowlerStats(i,p.id);return `<tr><td>${esc(p.name)}</td><td>${ballsToOver(z.b)}</td><td>${z.r}</td><td>${z.w}</td><td>${z.econ}</td></tr>`}).join('')}</table></div></div>`}
function newEvent(){if(db.teams.length<2)return toast('Create at least 2 teams');modal(`<h2>New Competition</h2><div class="field"><label>NAME</label><input id="cn"></div><div class="field"><label>FORMAT</label><select id="cf"><option>League</option><option>Knockout</option></select></div><div class="field"><label>OVERS</label><input id="co" type="number" min="2" max="50" value="10"></div><div class="field"><label>TEAMS</label>${db.teams.map(t=>`<label style="display:block;margin:7px 0"><input class="ct" type="checkbox" value="${t.id}" checked> ${esc(t.name)}</label>`).join('')}</div><button class="btn block" data-act="saveEvent">Create Competition</button>`)}
function saveEvent(){const name=$('cn')?.value.trim(),format=$('cf')?.value,overs=Math.max(2,Math.min(50,parseInt($('co')?.value)||10)),ids=[...document.querySelectorAll('.ct:checked')].map(x=>x.value);if(!name)return toast('Enter competition name');if(ids.length<2)return toast('Select at least 2 teams');const c={id:uid(),name,format,overs,teamIds:ids,fixtures:[]};if(format==='League'){for(let a=0;a<ids.length;a++)for(let b=a+1;b<ids.length;b++)c.fixtures.push({a:ids[a],b:ids[b]})}else{for(let i=0;i+1<ids.length;i+=2)c.fixtures.push({a:ids[i],b:ids[i+1]})}db.competitions.push(c);persist();closeModal();render();toast('Competition created')}
function showEvent(id){const c=db.competitions.find(x=>x.id===id);if(!c)return;modal(`<div class="row between"><h2>${esc(c.name)}</h2><button class="icon" data-act="close">✕</button></div><p class="muted">${c.format} · ${c.overs} overs</p><div class="section">Fixtures</div><div class="list">${c.fixtures.map((f,i)=>`<div class="listitem"><b>${esc(team(f.a)?.name)} vs ${esc(team(f.b)?.name)}</b><small class="muted">Match ${i+1}</small></div>`).join('')}</div>`)}
function backup(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='cricpro-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function routeClick(e){const n=e.target.closest('[data-nav]');if(n){closeModal();page=n.dataset.nav;active=null;render();return}const t=e.target.closest('[data-team]');if(t)return editTeam(t.dataset.team);const mm=e.target.closest('[data-match]');if(mm){active=mm.dataset.match;page='score';render();return}const ev=e.target.closest('[data-event]');if(ev)return showEvent(ev.dataset.event);const rm=e.target.closest('[data-remove-player]');if(rm)return removePlayer(rm.dataset.teamId,rm.dataset.removePlayer);const ap=e.target.closest('[data-add-player]');if(ap)return addPlayer(ap.dataset.addPlayer);const sm=e.target.closest('[data-start-match]');if(sm)return startMatch(sm.dataset.startMatch);const r=e.target.closest('[data-run]');if(r)return addBall('run',+r.dataset.run);const x=e.target.closest('[data-extra]');if(x)return addBall(x.dataset.extra);const a=e.target.closest('[data-act]');if(!a)return;({close:closeModal,newTeam,saveTeam,importCSV,newMatch,createMatch,wicket,confirmWicket,undo,swap,changeBowler,setBowler,endInnings:()=>{const m=match(active);if(m){finishInnings(m);render()}},scorecard,newEvent,saveEvent,backup}[a.dataset.act]||(()=>{}))()}
document.addEventListener('click',routeClick);
function selfTest(){const old=clone(db),oldPage=page,oldActive=active;let ok=[],fail=[];const test=(name,fn)=>{try{fn();ok.push(name)}catch(e){fail.push(name+': '+e.message)}};try{db=clone(DEFAULT);const ta={id:'A',name:'Alpha',short:'ALP',players:[1,2,3].map(n=>({id:'a'+n,name:'A'+n,role:'Player'}))},tb={id:'B',name:'Beta',short:'BET',players:[1,2,3].map(n=>({id:'b'+n,name:'B'+n,role:'Player'}))};db.teams.push(ta,tb);const m={id:'M',teamA:'A',teamB:'B',overs:2,type:'Test',status:'live',innings:[newInn('A','B')],currentInnings:0};db.matches.push(m);active='M';page='score';test('score zero',()=>{if(runs(m.innings[0])!==0)throw Error('bad zero')});test('single increments',()=>{addBall('run',1);if(runs(m.innings[0])!==1)throw Error('run')});test('wide not legal',()=>{const before=legalBalls(m.innings[0]);addBall('wide');if(legalBalls(m.innings[0])!==before)throw Error('wide legal')});test('boundary',()=>{addBall('run',4);if(runs(m.innings[0])!==6)throw Error('total')});test('undo',()=>{const before=m.innings[0].balls.length;undo();if(m.innings[0].balls.length!==before-1)throw Error('undo')});test('overs format',()=>{if(ballsToOver(7)!=='1.1')throw Error('overs')});test('stats',()=>{if(batterStats(m.innings[0],'a1').r<0)throw Error('stats')});}finally{db=old;page=oldPage;active=oldActive;persist()}return{passed:ok.length,failed:fail.length,ok,fail}}
window.CricProQA={selfTest};
render();
if(location.search.includes('selftest=1')){const r=selfTest();document.body.innerHTML=`<pre id="selftest">${esc(JSON.stringify(r,null,2))}</pre>`}
})();