(()=>{'use strict';
const R=window.CricketRules;if(!R)return;
const KEY='cricpro_v4';
const getDB=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"teams":[],"matches":[]}')}catch(e){return {teams:[],matches:[]}}};
const pname=(db,id)=>{for(const t of db.teams||[]){const p=(t.players||[]).find(x=>x.id===id);if(p)return p.name}return 'Player'};
const tname=(db,id)=>(db.teams||[]).find(t=>t.id===id)?.name||'Team';
const inningsOvers=i=>{const a=[];for(const e of i?.events||[]){if(e.kind!=='delivery')continue;const oi=Number(e.overIndex||0);a[oi]=(a[oi]||0)+Number(e.teamRuns||0)}return a;
const partnership=i=>{if(!i)return {runs:0,balls:0};let runs=0,balls=0;for(let n=(i.events||[]).length-1;n>=0;n--){const e=i.events[n];if(e.wicket&&e.wicket.counts!==false)break;runs+=Number(e.teamRuns||0);if(e.kind==='delivery'&&e.legal)balls++}return {runs,balls}};
const recentComments=(db,i)=>{if(!i)return [];return (i.events||[]).slice().reverse().slice(0,12).map(e=>{let text='';let cls='';if(e.wicket&&e.wicket.counts!==false){cls='wicket';text=`WICKET! ${pname(db,e.wicket.player)} — ${e.wicket.type}.`}else if(e.kind==='delivery'){if(e.batRuns===6){cls='boundary';text=`SIX! ${pname(db,e.striker)} sends it all the way.`}else if(e.batRuns===4){cls='boundary';text=`FOUR! ${pname(db,e.striker)} finds the boundary.`}else if(e.noBall)text=`No ball${e.batRuns?`, ${e.batRuns} off the bat`:''}.`;else if(e.wide)text=`Wide — ${e.wideRuns||1} run${(e.wideRuns||1)>1?'s':''}.`;else if(e.byeRuns)text=`${e.byeRuns} bye${e.byeRuns>1?'s':''}.`;else if(e.legByeRuns)text=`${e.legByeRuns} leg bye${e.legByeRuns>1?'s':''}.`;else if(e.batRuns===0)text='Dot ball. No run.';else text=`${e.batRuns} run${e.batRuns>1?'s':''} to ${pname(db,e.striker)}.`}else if(e.kind==='penalty')text=`Penalty: ${e.teamRuns} runs.`;else if(e.kind==='dead')text='Dead ball — delivery does not count.';return {text,cls,label:e.label||''}}).filter(x=>x.text)};
function insightHTML(db,m){if(!m?.innings?.length)return '';const i=m.innings[m.currentInnings||0]||m.innings[m.innings.length-1];if(!i)return '';const ovs=inningsOvers(i),max=Math.max(1,...ovs),pp=partnership(i),bf=R.batterFigures(i,i.striker),nf=R.batterFigures(i,i.nonStriker),comments=recentComments(db,i);const last5=(i.events||[]).filter(e=>e.kind==='delivery'&&e.legal).slice(-30);const rr5=last5.length?((last5.reduce((s,e)=>s+Number(e.teamRuns||0),0)/(last5.length/6)).toFixed(2)):'0.00';const boundaryRuns=(i.events||[]).reduce((s,e)=>s+(e.boundary?Number(e.batRuns||0):0),0);const total=R.total(i)||1;const bars=ovs.map((v,n)=>`<div class="cp-bar ${v>=10?'hot':''}" style="height:${Math.max(7,Math.round(v/max*100))}%" title="Over ${n+1}: ${v}"></div>`).join('')||'<div class="cp-bar" style="height:7%"></div>';const labs=ovs.map((_,n)=>`<span>${n+1}</span>`).join('');return `<section class="cp-pro-insights"><div class="cp-insight-grid"><div class="cp-kpi"><small>Current RR</small><b>${(R.total(i)/(Math.max(1,R.legalBalls(i))/6)).toFixed(2)}</b></div><div class="cp-kpi"><small>Last 5 overs</small><b>${rr5}</b></div><div class="cp-kpi"><small>Boundary %</small><b>${Math.round(boundaryRuns/total*100)}%</b></div></div><div class="cp-panel"><h3>Run progression</h3><div class="cp-chart">${bars}</div><div class="cp-chart-labels">${labs}</div></div><div class="cp-panel"><h3>Current partnership</h3><div class="cp-partnership"><div class="cp-ring" style="--pct:${Math.min(100,Math.round(pp.runs/Math.max(1,R.total(i))*100))}%"><b>${pp.runs}</b></div><div><b>${pname(db,i.striker)} & ${pname(db,i.nonStriker)}</b><div class="muted">${pp.runs} runs • ${pp.balls} balls</div><small>${pname(db,i.striker)} ${bf.runs} (${bf.balls}) SR ${bf.sr} · ${pname(db,i.nonStriker)} ${nf.runs} (${nf.balls}) SR ${nf.sr}</small></div></div></div><div class="cp-panel"><h3>Auto commentary</h3><div class="cp-commentary">${comments.map(c=>`<div class="cp-comment ${c.cls}"><b>${c.label||'•'}</b> ${c.text}</div>`).join('')||'<div class="muted">Commentary appears as the match progresses.</div>'}</div></div></section>`}
function statsHTML(db){const bat={},bowl={};for(const m of db.matches||[])for(const i of m.innings||[]){for(const pid of i.battingXI||[]){const f=R.batterFigures(i,pid);const x=bat[pid]||(bat[pid]={id:pid,name:pname(db,pid),runs:0,balls:0,fours:0,sixes:0,outs:0,innings:0});x.runs+=f.runs;x.balls+=f.balls;x.fours+=f.fours;x.sixes+=f.sixes;x.innings++;if(f.out!=='not out')x.outs++}for(const pid of i.bowlingXI||[]){const f=R.bowlerFigures(i,pid);const x=bowl[pid]||(bowl[pid]={id:pid,name:pname(db,pid),runs:0,balls:0,wickets:0});x.runs+=f.runs;x.balls+=f.balls;x.wickets+=f.wickets}}
const bats=Object.values(bat).sort((a,b)=>b.runs-a.runs),bows=Object.values(bowl).sort((a,b)=>b.wickets-a.wickets||a.runs-b.runs);const rank=(a,type)=>a.slice(0,12).map((x,n)=>{const avg=type==='bat'?(x.runs/Math.max(1,x.outs)).toFixed(1):(x.balls?x.runs/(x.balls/6):0).toFixed(2);const sr=type==='bat'?(x.balls?x.runs*100/x.balls:0).toFixed(1):`${Math.floor(x.balls/6)}.${x.balls%6}`;return `<div class="cp-rank"><span class="num">${n+1}</span><div class="meta"><b>${x.name}</b><small>${type==='bat'?`${x.fours} fours • ${x.sixes} sixes`:`${sr} overs`}</small></div><div class="value"><b>${type==='bat'?x.runs:x.wickets}</b><small>${type==='bat'?`Avg ${avg} · SR ${sr}`:`Econ ${avg}`}</small></div></div>`}).join('');return `<div class="cp-panel"><h3>Batting leaders</h3>${rank(bats,'bat')||'<div class="muted">No batting data yet.</div>'}</div><div class="cp-panel"><h3>Bowling leaders</h3>${rank(bows,'bowl')||'<div class="muted">No bowling data yet.</div>'}</div>`}
function enhance(){const db=getDB();const app=document.getElementById('app');if(!app)return;const scoreMain=app.querySelector('.scorecardmain');if(scoreMain&&!app.querySelector('.cp-pro-insights')){const live=(db.matches||[]).find(m=>m.status==='live')||(db.matches||[]).slice(-1)[0];if(live)scoreMain.insertAdjacentHTML('afterend',insightHTML(db,live))}const h2=[...app.querySelectorAll('h2')].find(x=>/Statistics/i.test(x.textContent));if(h2&&!app.querySelector('.cp-rank')){const anchor=app.querySelector('.statgrid');(anchor||h2).insertAdjacentHTML('afterend',statsHTML(db))}}
let lastSig='';function watchEvents(){const db=getDB(),m=(db.matches||[]).find(x=>x.status==='live');if(!m)return;const i=m.innings?.[m.currentInnings||0],e=i?.events?.[i.events.length-1];if(!e)return;const sig=`${m.id}:${m.currentInnings}:${i.events.length}:${e.label||e.kind}`;if(!lastSig){lastSig=sig;return}if(sig===lastSig)return;lastSig=sig;if(e.wicket&&e.wicket.counts!==false)pop('wicket','🏏','WICKET',pname(db,e.wicket.player));else if(e.kind==='delivery'&&e.batRuns===6)pop('six','🚀','SIX','MAXIMUM');else if(e.kind==='delivery'&&e.batRuns===4)pop('four','⚡','FOUR','BOUNDARY');else if(e.kind==='delivery'&&e.noBall)pop('freehit','🔥','NO BALL','FREE HIT NEXT');setTimeout(enhance,60)}
function pop(cls,icon,big,sub){document.querySelector('.cp-event-pop')?.remove();const d=document.createElement('div');d.className='cp-event-pop';d.innerHTML=`<div class="cp-event-card ${cls}"><div class="icon">${icon}</div><strong>${big}</strong><span>${sub}</span></div>`;document.body.appendChild(d);if(cls==='four'||cls==='six'){for(let n=0;n<18;n++){const c=document.createElement('i');c.className='cp-confetti';c.style.left=(5+Math.random()*90)+'vw';c.style.top=(-5-Math.random()*25)+'vh';c.style.background=['#2563eb','#16a66b','#f2a900','#d83b4d','#7047c7'][n%5];c.style.animationDelay=(Math.random()*.25)+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),1400)}}setTimeout(()=>d.remove(),900)}
const obs=new MutationObserver(()=>{clearTimeout(window.__cpEnh);window.__cpEnh=setTimeout(enhance,30)});window.addEventListener('DOMContentLoaded',()=>{const app=document.getElementById('app');if(app)obs.observe(app,{childList:true,subtree:true});enhance();setInterval(watchEvents,180)});})();